print('Please dont fail me')
print('    ____________')
print('   /            \ ')
print('  /              \ ')
print(' /    /\    /\    \ ')
print('|     \/    \/     |')
print('|                  |')
print('|    __________    |')
print('|    \        /    |')
print(' \    \______/    /')
print('  \              /')
print('   \____________/')
