import turtle

wn = turtle.Screen()
wn.bgcolor("magenta3")

turtle.shape("turtle")
turtle.pencolor("green3")
turtle.fillcolor("purple")
turtle.begin_fill()
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.end_fill()

turtle.speed(0)
turtle.pu()
turtle.goto(-150, 200)
turtle.pd()
turtle.pensize(5)
turtle.pencolor("blue4")
turtle.fillcolor("orange2")
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()

turtle.pu()
turtle.goto(-150, -150)
turtle.pd()
turtle.stamp()
turtle.pu()
turtle.goto(-150, -120)
turtle.pd()
turtle.stamp()
turtle.pu()
turtle.goto(-150, -90)
turtle.pd()
turtle.stamp()
turtle.pu()

turtle.home
turtle.shapesize(2,2)
